🔧 ci: Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -4,23 +4,55 @@ on:
   push:
     branches:
       - main
+    tags:
+      - "v*"
 
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Bump version and push tag
-      id: get_tag
-      uses: mathieudutour/github-tag-action@v6.1
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: Create release
-      uses: ncipollo/release-action@v1
-      with:
-        tag: ${{ steps.get_tag.outputs.new_tag }}
-        name: Release ${{ steps.get_tag.outputs.new_tag }}
-        body: ${{ steps.get_tag.outputs.changelog }}
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Extract tag name
+        id: get_version
+        run: echo "::set-output name=image_version::${GITHUB_REF#refs/tags/}"
+
+      - name: Check tag format
+        run: |
+          TAG_NAME="${{ steps.get_version.outputs.image_version }}"
+          if ! [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
+            echo "Tag $TAG_NAME does not meet the required format 'vX.Y.Z'."
+            exit 1
+          fi
+
+      - name: Publish as GitHub Package
+        uses: docker/build-push-action@v5
+        with:
+          provenance: false
+          context: .
+          file: ./Dockerfile
+          platforms: linux/amd64,linux/arm64
+          push: true
+          tags: |
+            ghcr.io/${{ github.repository }}:latest
+            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.image_version }}
+
+      - name: Create Release
+        if: success()
+        uses: ncipollo/release-action@v1
+        with:
+          tag: ${{ steps.get_version.outputs.image_version }}
+          name: Release ${{ steps.get_version.outputs.image_version }}
+          token: ${{ secrets.GITHUB_TOKEN }}
